version: '3.8'

services:
  app:
    build: 
      context: .
      target: development
    ports:
      - "5173:5173"  # Client
      - "3000:3000"  # Server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/itaicy
      - PORT=3000
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=itaicy
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
